/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Admin Auth */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAuthCheckResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/landlords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Landlords */
        get: {
            parameters: {
                query?: {
                    status?: ("new" | "contacted" | "listed" | "inactive") | null;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLandlordListResponse"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/landlords/{landlord_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Landlord */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    landlord_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLandlordDetail"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Admin Landlord */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    landlord_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminLandlordUpdateRequest"];
                };
            };
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLandlordDetail"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/admin/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Leads */
        get: {
            parameters: {
                query?: {
                    status?: ("new" | "contacted" | "qualified" | "viewing_arranged" | "offer_made" | "let_agreed" | "completed" | "lost") | null;
                    assigned_agent_id?: string | null;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLeadListResponse"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/leads/{renter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Lead */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    renter_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLeadDetail"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Admin Lead */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    renter_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminLeadUpdateRequest"];
                };
            };
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLeadDetail"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/admin/leads/{renter_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Lead Conversations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    renter_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminConversation"][];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Chat Reply */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatResponse"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/landlords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Landlord Intake */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LandlordIntakeRequest"];
                };
            };
            responses: {
                /** @description Successful Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LandlordIntakeResponse"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Renter Lead */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenterLeadRequest"];
                };
            };
            responses: {
                /** @description Successful Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RenterLeadResponse"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminAuthCheckResponse */
        AdminAuthCheckResponse: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Email */
            email: string;
            /**
             * Role
             * @constant
             */
            role: "admin";
        };
        /** AdminConversation */
        AdminConversation: {
            /** Ai Summary */
            ai_summary?: string | null;
            /**
             * Channel
             * @enum {string}
             */
            channel: "website" | "whatsapp" | "facebook";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** External Id */
            external_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent Score Output */
            intent_score_output?: number | null;
            /** Renter Id */
            renter_id?: string | null;
            /** Session Id */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            transcript?: components["schemas"]["Transcript"];
            /** Updated At */
            updated_at?: string | null;
        };
        /** AdminLandlordDetail */
        AdminLandlordDetail: {
            /** Advanced Rent Interest */
            advanced_rent_interest?: boolean | null;
            /** Asking Rent */
            asking_rent?: string | null;
            /** Available From */
            available_from?: string | null;
            /** Bedrooms */
            bedrooms?: number | null;
            /**
             * Consent At
             * Format: date-time
             */
            consent_at: string;
            /** Consent Given */
            consent_given: boolean;
            /** Consent Version */
            consent_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Listing Interest */
            listing_interest?: boolean | null;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            /** Property Address */
            property_address?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "listed" | "inactive";
            /** Updated At */
            updated_at?: string | null;
        };
        /** AdminLandlordListItem */
        AdminLandlordListItem: {
            /** Advanced Rent Interest */
            advanced_rent_interest?: boolean | null;
            /** Asking Rent */
            asking_rent?: string | null;
            /** Available From */
            available_from?: string | null;
            /** Bedrooms */
            bedrooms?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Listing Interest */
            listing_interest?: boolean | null;
            /** Phone */
            phone?: string | null;
            /** Property Address */
            property_address?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "listed" | "inactive";
            /** Updated At */
            updated_at?: string | null;
        };
        /** AdminLandlordListResponse */
        AdminLandlordListResponse: {
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Results */
            results: components["schemas"]["AdminLandlordListItem"][];
            /** Total */
            total: number;
        };
        /** AdminLandlordUpdateRequest */
        AdminLandlordUpdateRequest: {
            /** Notes */
            notes?: string | null;
            /** Status */
            status?: ("new" | "contacted" | "listed" | "inactive") | null;
        };
        /** AdminLeadDetail */
        AdminLeadDetail: {
            /** Accessibility Needs */
            accessibility_needs?: string | null;
            /** Annual Income Range */
            annual_income_range?: string | null;
            /** Areas Preferred */
            areas_preferred?: string[] | null;
            /** Assigned Agent Id */
            assigned_agent_id?: string | null;
            /** Bedrooms Required */
            bedrooms_required?: number | null;
            /**
             * Consent At
             * Format: date-time
             */
            consent_at: string;
            /** Consent Given */
            consent_given: boolean;
            /** Consent Version */
            consent_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Housing */
            current_housing?: ("renting" | "family" | "owning") | null;
            /** Deposit Availability */
            deposit_availability?: ("full" | "partial" | "limited") | null;
            /** Email */
            email?: string | null;
            /** Employment Status */
            employment_status?: ("employed_full" | "employed_part" | "self_employed" | "student" | "universal_credit" | "other") | null;
            fintech_flags?: components["schemas"]["JsonObject"];
            /** Full Name */
            full_name?: string | null;
            /** Furnished Preference */
            furnished_preference?: ("furnished" | "unfurnished" | "no_preference") | null;
            /** Has Guarantor */
            has_guarantor?: ("yes" | "no" | "unsure") | null;
            /** Has Rented Before */
            has_rented_before?: boolean | null;
            /** How Heard */
            how_heard?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent Score */
            intent_score: number;
            /**
             * Lead Status
             * @enum {string}
             */
            lead_status: "new" | "contacted" | "qualified" | "viewing_arranged" | "offer_made" | "let_agreed" | "completed" | "lost";
            /** Max Rent */
            max_rent?: string | null;
            /** Move In By */
            move_in_by?: string | null;
            /** Move In From */
            move_in_from?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pets */
            pets?: string | null;
            /** Phone */
            phone?: string | null;
            /** Scraye Introduction Id */
            scraye_introduction_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Source Channel
             * @enum {string}
             */
            source_channel: "website" | "whatsapp" | "facebook" | "referral";
            /** Updated At */
            updated_at?: string | null;
        };
        /** AdminLeadListItem */
        AdminLeadListItem: {
            /** Accessibility Needs */
            accessibility_needs?: string | null;
            /** Annual Income Range */
            annual_income_range?: string | null;
            /** Areas Preferred */
            areas_preferred?: string[] | null;
            /** Assigned Agent Id */
            assigned_agent_id?: string | null;
            /** Bedrooms Required */
            bedrooms_required?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Housing */
            current_housing?: ("renting" | "family" | "owning") | null;
            /** Deposit Availability */
            deposit_availability?: ("full" | "partial" | "limited") | null;
            /** Email */
            email?: string | null;
            /** Employment Status */
            employment_status?: ("employed_full" | "employed_part" | "self_employed" | "student" | "universal_credit" | "other") | null;
            fintech_flags?: components["schemas"]["JsonObject"];
            /** Full Name */
            full_name?: string | null;
            /** Furnished Preference */
            furnished_preference?: ("furnished" | "unfurnished" | "no_preference") | null;
            /** Has Guarantor */
            has_guarantor?: ("yes" | "no" | "unsure") | null;
            /** Has Rented Before */
            has_rented_before?: boolean | null;
            /** How Heard */
            how_heard?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent Score */
            intent_score: number;
            /**
             * Lead Status
             * @enum {string}
             */
            lead_status: "new" | "contacted" | "qualified" | "viewing_arranged" | "offer_made" | "let_agreed" | "completed" | "lost";
            /** Max Rent */
            max_rent?: string | null;
            /** Move In By */
            move_in_by?: string | null;
            /** Move In From */
            move_in_from?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pets */
            pets?: string | null;
            /** Phone */
            phone?: string | null;
            /** Scraye Introduction Id */
            scraye_introduction_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Source Channel
             * @enum {string}
             */
            source_channel: "website" | "whatsapp" | "facebook" | "referral";
            /** Updated At */
            updated_at?: string | null;
        };
        /** AdminLeadListResponse */
        AdminLeadListResponse: {
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Results */
            results: components["schemas"]["AdminLeadListItem"][];
            summary: components["schemas"]["AdminLeadSummary"];
            /** Total */
            total: number;
        };
        /** AdminLeadSummary */
        AdminLeadSummary: {
            /** Hot Leads Pending */
            hot_leads_pending: number;
            /** New Leads Today */
            new_leads_today: number;
            /** Pipeline By Stage */
            pipeline_by_stage: {
                [key: string]: number;
            };
        };
        /** AdminLeadUpdateRequest */
        AdminLeadUpdateRequest: {
            /** Assigned Agent Id */
            assigned_agent_id?: string | null;
            /** Lead Status */
            lead_status?: ("new" | "contacted" | "qualified" | "viewing_arranged" | "offer_made" | "let_agreed" | "completed" | "lost") | null;
            /** Notes */
            notes?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Renter Id */
            renter_id?: string | null;
            /** Session Id */
            session_id: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Session Id */
            session_id: string;
            /** Suggested Action */
            suggested_action?: "show_intake_form" | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        JsonObject: {
            [key: string]: unknown;
        };
        /** LandlordIntakeRequest */
        LandlordIntakeRequest: {
            /**
             * Advanced Rent Interest
             * @default false
             */
            advanced_rent_interest: boolean;
            /** Asking Rent */
            asking_rent: number | string;
            /** Available From */
            available_from?: string | null;
            /** Bedrooms */
            bedrooms: number;
            /**
             * Consent Given
             * @constant
             */
            consent_given: true;
            /** Consent Version */
            consent_version: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Listing Interest
             * @default false
             */
            listing_interest: boolean;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone: string;
            /** Property Address */
            property_address: string;
        };
        /** LandlordIntakeResponse */
        LandlordIntakeResponse: {
            /**
             * Landlord Id
             * Format: uuid
             */
            landlord_id: string;
            /** Message */
            message: string;
        };
        /** RenterLeadRequest */
        RenterLeadRequest: {
            /** Accessibility Needs */
            accessibility_needs?: string | null;
            /** Annual Income Range */
            annual_income_range?: string | null;
            /** Areas Preferred */
            areas_preferred: string[];
            /** Bedrooms Required */
            bedrooms_required: number;
            /**
             * Consent Given
             * @constant
             */
            consent_given: true;
            /** Consent Version */
            consent_version: string;
            /**
             * Current Housing
             * @enum {string}
             */
            current_housing: "renting" | "family" | "owning";
            /**
             * Deposit Availability
             * @enum {string}
             */
            deposit_availability: "full" | "partial" | "limited";
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Employment Status
             * @enum {string}
             */
            employment_status: "employed_full" | "employed_part" | "self_employed" | "student" | "universal_credit" | "other";
            /** Full Name */
            full_name: string;
            /**
             * Furnished Preference
             * @default no_preference
             * @enum {string}
             */
            furnished_preference: "furnished" | "unfurnished" | "no_preference";
            /**
             * Has Guarantor
             * @enum {string}
             */
            has_guarantor: "yes" | "no" | "unsure";
            /** Has Rented Before */
            has_rented_before?: boolean | null;
            /** How Heard */
            how_heard?: string | null;
            /** Max Rent */
            max_rent: number | string;
            /** Move In By */
            move_in_by?: string | null;
            /** Move In From */
            move_in_from?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pets */
            pets?: string | null;
            /** Phone */
            phone: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Source Channel
             * @default website
             * @enum {string}
             */
            source_channel: "website" | "whatsapp" | "facebook" | "referral";
        };
        /** RenterLeadResponse */
        RenterLeadResponse: {
            /** Message */
            message: string;
            /**
             * Renter Id
             * Format: uuid
             */
            renter_id: string;
        };
        Transcript: {
            [key: string]: unknown;
        }[];
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
